name: Hello Barsoom

description: "Greet someone"

inputs:
  who-to-greet:
    description: 'Name'
    required: true
    default: 'Barsoom'

outputs:
  greeting:
    description: 'How we greeted you'

runs:
  using: 'node20'
  main: dist/index.js